### ISSUE TITLE
NullPointerException reading DBF file opened without directory

### ISSUE THREAD

**Issue by simoc** [DANS-KNAW/dans-dbf-lib#4]
If I open a DBF file using a bare filename without a directory, then reading from the file fails.  My test program begins:

```
11  File dbfFile = new File("cars.dbf");
12  Table table = new Table(dbfFile);
13  table.open(IfNonExistent.ERROR);
14  List<Field> fields = table.getFields();
15  Iterator<Record> it = table.recordIterator();
16  while (it.hasNext())
17  {
18    Record record = it.next();
```

The exception is:

```
Exception in thread "main" java.lang.NullPointerException
at java.io.File.<init>(File.java:277)
at nl.knaw.dans.common.dbflib.Util.getMemoFile(Util.java:146)
at nl.knaw.dans.common.dbflib.Table.openMemo(Table.java:600)
at nl.knaw.dans.common.dbflib.Table.ensureMemoOpened(Table.java:570)
at nl.knaw.dans.common.dbflib.Table.readMemo(Table.java:552)
at nl.knaw.dans.common.dbflib.Table.getRecordAt(Table.java:698)
at nl.knaw.dans.common.dbflib.Table$RecordIterator.next(Table.java:105)
at nl.knaw.dans.common.dbflib.Table$RecordIterator.next(Table.java:44)
at DansDbfDemo.main(DansDbfDemo.java:18)
```

If I change the filename to ./cars.dbf then the program works correctly.

**Comment by janvanmansum** [comment]
I suspect that `getParent` [here](https://github.com/DANS-KNAW/dans-dbf-lib/blob/master/src/main/java/nl/knaw/dans/common/dbflib/Util.java#L144) returns `null` if the parent is not explicitly part of the path. To fix this you could first [get the canonical file](https://docs.oracle.com/javase/8/docs/api/java/io/File.html#getCanonicalFile--) which would presumably always return a parent file (i.e. the directory containing the `dbf`-file). If you do that make sure you program defensively and take into account the possibility that `getCanonicalFile` throws an I/O exception.

**Comment by simoc** [comment]
42b8768e38fe870a3896d8de5dd22b7d5d3712c6
